image: tmaier/docker-compose:latest

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

.build_template: &build_template
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - echo "$DH_TOKEN" | docker login --username $DH_USER --password-stdin
  script:
    - ./buildimage.sh "$BUILD_TARGET" "$DH_REGISTRY" "$CI_COMMIT_TAG"

build_prod:
  <<: *build_template
  variables:
    BUILD_TARGET: prod

build_dev:
  <<: *build_template
  variables:
    BUILD_TARGET: dev